#!/bin/bash

usage ()
{
  echo 'Usage: gitmail -m <e-mail>'
  exit
}

[ "$#" -ne 2 ] && usage

while getopts m: flag
do
    case ${flag} in
        m) mail=${OPTARG};;
    esac
done

git config user.email $mail
